// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package torram

import (
	fmt "fmt"
	io "io"
	reflect "reflect"
	sync "sync"

	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

var (
	md_Utxo          protoreflect.MessageDescriptor
	fd_Utxo_txId     protoreflect.FieldDescriptor
	fd_Utxo_vout     protoreflect.FieldDescriptor
	fd_Utxo_address  protoreflect.FieldDescriptor
	fd_Utxo_amount   protoreflect.FieldDescriptor
	fd_Utxo_lockTime protoreflect.FieldDescriptor
	fd_Utxo_isStaked protoreflect.FieldDescriptor
)

func init() {
	file_torram_torram_utxo_proto_init()
	md_Utxo = File_torram_torram_utxo_proto.Messages().ByName("Utxo")
	fd_Utxo_txId = md_Utxo.Fields().ByName("txId")
	fd_Utxo_vout = md_Utxo.Fields().ByName("vout")
	fd_Utxo_address = md_Utxo.Fields().ByName("address")
	fd_Utxo_amount = md_Utxo.Fields().ByName("amount")
	fd_Utxo_lockTime = md_Utxo.Fields().ByName("lockTime")
	fd_Utxo_isStaked = md_Utxo.Fields().ByName("isStaked")
}

var _ protoreflect.Message = (*fastReflection_Utxo)(nil)

type fastReflection_Utxo Utxo

func (x *Utxo) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Utxo)(x)
}

func (x *Utxo) slowProtoReflect() protoreflect.Message {
	mi := &file_torram_torram_utxo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Utxo_messageType fastReflection_Utxo_messageType
var _ protoreflect.MessageType = fastReflection_Utxo_messageType{}

type fastReflection_Utxo_messageType struct{}

func (x fastReflection_Utxo_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Utxo)(nil)
}
func (x fastReflection_Utxo_messageType) New() protoreflect.Message {
	return new(fastReflection_Utxo)
}
func (x fastReflection_Utxo_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Utxo
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Utxo) Descriptor() protoreflect.MessageDescriptor {
	return md_Utxo
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Utxo) Type() protoreflect.MessageType {
	return _fastReflection_Utxo_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Utxo) New() protoreflect.Message {
	return new(fastReflection_Utxo)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Utxo) Interface() protoreflect.ProtoMessage {
	return (*Utxo)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Utxo) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.TxId != "" {
		value := protoreflect.ValueOfString(x.TxId)
		if !f(fd_Utxo_txId, value) {
			return
		}
	}
	if x.Vout != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Vout)
		if !f(fd_Utxo_vout, value) {
			return
		}
	}
	if x.Address != "" {
		value := protoreflect.ValueOfString(x.Address)
		if !f(fd_Utxo_address, value) {
			return
		}
	}
	if x.Amount != "" {
		value := protoreflect.ValueOfString(x.Amount)
		if !f(fd_Utxo_amount, value) {
			return
		}
	}
	if x.LockTime != uint64(0) {
		value := protoreflect.ValueOfUint64(x.LockTime)
		if !f(fd_Utxo_lockTime, value) {
			return
		}
	}
	if x.IsStaked != false {
		value := protoreflect.ValueOfBool(x.IsStaked)
		if !f(fd_Utxo_isStaked, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Utxo) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "torram.torram.Utxo.txId":
		return x.TxId != ""
	case "torram.torram.Utxo.vout":
		return x.Vout != uint64(0)
	case "torram.torram.Utxo.address":
		return x.Address != ""
	case "torram.torram.Utxo.amount":
		return x.Amount != ""
	case "torram.torram.Utxo.lockTime":
		return x.LockTime != uint64(0)
	case "torram.torram.Utxo.isStaked":
		return x.IsStaked != false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: torram.torram.Utxo"))
		}
		panic(fmt.Errorf("message torram.torram.Utxo does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Utxo) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "torram.torram.Utxo.txId":
		x.TxId = ""
	case "torram.torram.Utxo.vout":
		x.Vout = uint64(0)
	case "torram.torram.Utxo.address":
		x.Address = ""
	case "torram.torram.Utxo.amount":
		x.Amount = ""
	case "torram.torram.Utxo.lockTime":
		x.LockTime = uint64(0)
	case "torram.torram.Utxo.isStaked":
		x.IsStaked = false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: torram.torram.Utxo"))
		}
		panic(fmt.Errorf("message torram.torram.Utxo does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Utxo) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "torram.torram.Utxo.txId":
		value := x.TxId
		return protoreflect.ValueOfString(value)
	case "torram.torram.Utxo.vout":
		value := x.Vout
		return protoreflect.ValueOfUint64(value)
	case "torram.torram.Utxo.address":
		value := x.Address
		return protoreflect.ValueOfString(value)
	case "torram.torram.Utxo.amount":
		value := x.Amount
		return protoreflect.ValueOfString(value)
	case "torram.torram.Utxo.lockTime":
		value := x.LockTime
		return protoreflect.ValueOfUint64(value)
	case "torram.torram.Utxo.isStaked":
		value := x.IsStaked
		return protoreflect.ValueOfBool(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: torram.torram.Utxo"))
		}
		panic(fmt.Errorf("message torram.torram.Utxo does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Utxo) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "torram.torram.Utxo.txId":
		x.TxId = value.Interface().(string)
	case "torram.torram.Utxo.vout":
		x.Vout = value.Uint()
	case "torram.torram.Utxo.address":
		x.Address = value.Interface().(string)
	case "torram.torram.Utxo.amount":
		x.Amount = value.Interface().(string)
	case "torram.torram.Utxo.lockTime":
		x.LockTime = value.Uint()
	case "torram.torram.Utxo.isStaked":
		x.IsStaked = value.Bool()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: torram.torram.Utxo"))
		}
		panic(fmt.Errorf("message torram.torram.Utxo does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Utxo) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "torram.torram.Utxo.txId":
		panic(fmt.Errorf("field txId of message torram.torram.Utxo is not mutable"))
	case "torram.torram.Utxo.vout":
		panic(fmt.Errorf("field vout of message torram.torram.Utxo is not mutable"))
	case "torram.torram.Utxo.address":
		panic(fmt.Errorf("field address of message torram.torram.Utxo is not mutable"))
	case "torram.torram.Utxo.amount":
		panic(fmt.Errorf("field amount of message torram.torram.Utxo is not mutable"))
	case "torram.torram.Utxo.lockTime":
		panic(fmt.Errorf("field lockTime of message torram.torram.Utxo is not mutable"))
	case "torram.torram.Utxo.isStaked":
		panic(fmt.Errorf("field isStaked of message torram.torram.Utxo is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: torram.torram.Utxo"))
		}
		panic(fmt.Errorf("message torram.torram.Utxo does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Utxo) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "torram.torram.Utxo.txId":
		return protoreflect.ValueOfString("")
	case "torram.torram.Utxo.vout":
		return protoreflect.ValueOfUint64(uint64(0))
	case "torram.torram.Utxo.address":
		return protoreflect.ValueOfString("")
	case "torram.torram.Utxo.amount":
		return protoreflect.ValueOfString("")
	case "torram.torram.Utxo.lockTime":
		return protoreflect.ValueOfUint64(uint64(0))
	case "torram.torram.Utxo.isStaked":
		return protoreflect.ValueOfBool(false)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: torram.torram.Utxo"))
		}
		panic(fmt.Errorf("message torram.torram.Utxo does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Utxo) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in torram.torram.Utxo", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Utxo) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Utxo) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Utxo) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Utxo) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Utxo)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.TxId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Vout != 0 {
			n += 1 + runtime.Sov(uint64(x.Vout))
		}
		l = len(x.Address)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Amount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.LockTime != 0 {
			n += 1 + runtime.Sov(uint64(x.LockTime))
		}
		if x.IsStaked {
			n += 2
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Utxo)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.IsStaked {
			i--
			if x.IsStaked {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x30
		}
		if x.LockTime != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.LockTime))
			i--
			dAtA[i] = 0x28
		}
		if len(x.Amount) > 0 {
			i -= len(x.Amount)
			copy(dAtA[i:], x.Amount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Amount)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Address) > 0 {
			i -= len(x.Address)
			copy(dAtA[i:], x.Address)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Address)))
			i--
			dAtA[i] = 0x1a
		}
		if x.Vout != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Vout))
			i--
			dAtA[i] = 0x10
		}
		if len(x.TxId) > 0 {
			i -= len(x.TxId)
			copy(dAtA[i:], x.TxId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TxId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Utxo)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Utxo: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Utxo: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TxId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Vout", wireType)
				}
				x.Vout = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Vout |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Address = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Amount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field LockTime", wireType)
				}
				x.LockTime = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.LockTime |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IsStaked", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.IsStaked = bool(v != 0)
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: torram/torram/utxo.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Utxo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId     string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	Vout     uint64 `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount   string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	LockTime uint64 `protobuf:"varint,5,opt,name=lockTime,proto3" json:"lockTime,omitempty"`
	IsStaked bool   `protobuf:"varint,6,opt,name=isStaked,proto3" json:"isStaked,omitempty"`
}

func (x *Utxo) Reset() {
	*x = Utxo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_torram_torram_utxo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Utxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utxo) ProtoMessage() {}

// Deprecated: Use Utxo.ProtoReflect.Descriptor instead.
func (*Utxo) Descriptor() ([]byte, []int) {
	return file_torram_torram_utxo_proto_rawDescGZIP(), []int{0}
}

func (x *Utxo) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Utxo) GetVout() uint64 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *Utxo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Utxo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Utxo) GetLockTime() uint64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *Utxo) GetIsStaked() bool {
	if x != nil {
		return x.IsStaked
	}
	return false
}

var File_torram_torram_utxo_proto protoreflect.FileDescriptor

var file_torram_torram_utxo_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x2f, 0x74, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x2f,
	0x75, 0x74, 0x78, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x6f, 0x72, 0x72,
	0x61, 0x6d, 0x2e, 0x74, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x55, 0x74,
	0x78, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x76, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x53, 0x74,
	0x61, 0x6b, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x74,
	0x61, 0x6b, 0x65, 0x64, 0x42, 0x8d, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x6f, 0x72,
	0x72, 0x61, 0x6d, 0x2e, 0x74, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x42, 0x09, 0x55, 0x74, 0x78, 0x6f,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x18, 0x74, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x2f, 0x74, 0x6f, 0x72, 0x72, 0x61,
	0x6d, 0xa2, 0x02, 0x03, 0x54, 0x54, 0x58, 0xaa, 0x02, 0x0d, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d,
	0x2e, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0xca, 0x02, 0x0d, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d,
	0x5c, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0xe2, 0x02, 0x19, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d,
	0x5c, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x0e, 0x54, 0x6f, 0x72, 0x72, 0x61, 0x6d, 0x3a, 0x3a, 0x54, 0x6f,
	0x72, 0x72, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_torram_torram_utxo_proto_rawDescOnce sync.Once
	file_torram_torram_utxo_proto_rawDescData = file_torram_torram_utxo_proto_rawDesc
)

func file_torram_torram_utxo_proto_rawDescGZIP() []byte {
	file_torram_torram_utxo_proto_rawDescOnce.Do(func() {
		file_torram_torram_utxo_proto_rawDescData = protoimpl.X.CompressGZIP(file_torram_torram_utxo_proto_rawDescData)
	})
	return file_torram_torram_utxo_proto_rawDescData
}

var file_torram_torram_utxo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_torram_torram_utxo_proto_goTypes = []interface{}{
	(*Utxo)(nil), // 0: torram.torram.Utxo
}
var file_torram_torram_utxo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_torram_torram_utxo_proto_init() }
func file_torram_torram_utxo_proto_init() {
	if File_torram_torram_utxo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_torram_torram_utxo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Utxo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_torram_torram_utxo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_torram_torram_utxo_proto_goTypes,
		DependencyIndexes: file_torram_torram_utxo_proto_depIdxs,
		MessageInfos:      file_torram_torram_utxo_proto_msgTypes,
	}.Build()
	File_torram_torram_utxo_proto = out.File
	file_torram_torram_utxo_proto_rawDesc = nil
	file_torram_torram_utxo_proto_goTypes = nil
	file_torram_torram_utxo_proto_depIdxs = nil
}
